name: my CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Run a one-line script
      run: echo "just a line for test"
    - name: Run multi-line script
      run: |
        echo "An action thrat print multiple lines"
        echo "Second line to print"

